steps:
    # build the container image
    - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/nodejs-boilerplate/nodejs-boilerplate", "."]
    # push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/nodejs-boilerplate/nodejs-boilerplate"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
    args:
    [
    "beta",
    "run",
    "deploy",
    "--allow-unauthenticated",
    "nodejs-boilerplate",
    "--image",
    "gcr.io/nodejs-boilerplate/nodejs-boilerplate",
    "--region",
    "us-central1",
    "--platform",
    "managed",
    "--memory",
    "128Mi"
    ]
    images:
    - gcr.io/nodejs-boilerplate/nodejs-boilerplate